-- 配置表
INSERT INTO `mn_remind_conf`( `conf_id`, `conf_name`, `conf_type`, `conf_value`, `user_name`, `password`, `conf_desc`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '支付', 'url', 'http://pay-server-openapi1.choicesaas.cn/monitoring?format=pdf', 'pay', 'MeMydwfM330', '支付第1台服务器javameloady报告', 'zjf', sysdate(), 'zjf',  sysdate(), 0);
INSERT INTO `mn_remind_conf`( `conf_id`, `conf_name`, `conf_type`, `conf_value`, `user_name`, `password`, `conf_desc`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '扫码点餐', 'url', 'http://qrdish.choicesaas.cn/monitoring?format=pdf', 'qrdish', 'MeMydwfM33', '扫码老链路第1台服务器javameloady报告', 'zjf',  sysdate(), 'zjf',  sysdate(), 0);
INSERT INTO `mn_remind_conf`( `conf_id`, `conf_name`, `conf_type`, `conf_value`, `user_name`, `password`, `conf_desc`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '外卖', 'url', 'http://olp-takeout-cloud3-4.monitor.choicesaas.cn/monitoring?format=pdf', 'admin', '123456', '外卖javameloady报告', 'zjf',  sysdate(), 'zjf',  sysdate(), 0);
-- 收件人表
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'MC', 'fudanwei@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'MC', 'zhangliufeng@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'MC', 'qiaoyongjie@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'MC', 'songminghao@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'CC', 'wyb@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'CC', 'lzy02@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'CC', 'zxq@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'CC', 'xjw@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('44de6663-8414-4113-ad2c-18c441780da0', '', 'CC', 'zjf@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);

INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'MC', 'fudanwei@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'MC', 'zhangliufeng@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'MC', 'qiaoyongjie@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'MC', 'songminghao@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'CC', 'wyb@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'CC', 'lzy02@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'CC', 'zxq@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'CC', 'zjf@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('dc68dcf8-ae93-4103-aaf5-a854ac56847e', '', 'CC', 'xjw@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);

INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'MC', 'fudanwei@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'MC', 'zhangliufeng@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'MC', 'qiaoyongjie@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'MC', 'songminghao@jiumaojiu.com', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'CC', 'wyb@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'CC', 'lzy02@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'CC', 'zxq@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'CC', 'xjw@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
INSERT INTO `mn_remind_receive`(`conf_id`, `receive_name`, `receive_type`, `receive_mail`, `create_user`, `create_time`, `update_user`, `update_time`, `delete_flag`) VALUES ('9d8dc6ee-bbe7-4ef0-8aec-03200c2a0abd', '', 'CC', 'zjf@choicesoft.com.cn', 'zjf', sysdate(), 'zjf', sysdate(), 0);
